### ISSUE TITLE
Cannot solve

### ISSUE THREAD

**Issue by MystaraTheGreat** [megaboich/factorio-se-stargate#1]
I'm having an issue solving for a destination of [0.18046773886046, 0.29711777822653, 0.93763128205725]

It returns destination 0, but then returns 'value must be truthy' when trying to determine the intersection of the first face (25) with the line.  The obvious answer would be that the destination has been miscalculated, but I've checked and it's right (it's just the inversion of the coordinates in the log).

It feels like I'm missing something obvious....?

**Comment by megaboich** [comment]
Hi @MystaraTheGreat 

Indeed, it seems something is wrong with the `findClosestFaceToPoint` function. In your case, it returned the index 25, but when I visualize your destination point it is actually on the opposite side of the sphere, so there is no intersection with the destination vector at all. I will take a look at it when I have some time available, I like geometrical problems.

**Comment by megaboich** [comment]
Indeed, I didn't understand correctly what function [Triangle.containsPoint](https://threejs.org/docs/#api/en/math/Triangle.containsPoint) does, so implementation was not correct. It worked in my case by sheer coincidence.

Fixed in this commit.
https://github.com/megaboich/factorio-se-stargate/commit/fe592a8179f20388d265b0b04cdc6d0c75af296d
